#!/bin/bash
read main_string
read sub_string
position=$(echo "$main_string" | grep -b -o "$sub_string" | head -n 1 | cut -d ':' -f 1)
if [ -z "$position" ]; then
    echo "-1"
else
    echo "$((position + 1))"
fi
